### PR TITLE
Include what you use

### PR DESCRIPTION
**Pull request by krzysztofwos**
Fixes build error on Ubuntu Xenial/Clang 5.0

https://fix8engine.atlassian.net/browse/FX-858

### CODE REVIEW

**Comment by dakka** [comment]
Grand include covers this.

**Comment by fantastory** [comment]
Got same error on Ubuntu Xenial.
Could you add Grand step to 
https://github.com/fix8/fix8#building-on-linuxunix

**Comment by dakka** [comment]
Please resubmit your pull request to dev branch.

**Comment by fantastory** [comment]
In my PR I added minimum code required to compile library - there is another file that needs a cahnge.
https://github.com/fix8/fix8/pull/177
I guess other includes are inside poco dependency.

While I agree with Krzysztof, I think there is some more things to include there.
I have created pure main.cpp
```
#include "logger.hpp"
int main() {
    return 0;
}
```
And it shows lack of F8API or f8mutex.
Probably including some of the other library header could cover other std requirements.

Side note - you are using std::map there which is ordered_map, is not std::unordered_map faster?

**Pull request closed without merging**
