### PR TITLE
Add microsecond support for UTCTime* types

### PR DESCRIPTION
**Pull request by rbaxter1**
Added microsecond support for UTCTimestamp and UTCTimeOnly types leveraging new compiler option -T.

### CODE REVIEW

**Comment by rbaxter1** [comment]
Meant for dev branch

**Comment by dakka** [comment]
You can make a pull request - but I only see a merge here from dev to master. Your changes are not in this PR.

**Comment by rbaxter1** [comment]
Shall I make the changes on master and pull request there?

**Comment by dakka** [comment]
Make your pull request on dev branch. master is for releases.

**Pull request closed without merging**
