### PR TITLE
Add CMake find_package support.

### PR DESCRIPTION
**Pull request by ido**
To use this, in your CMakeLists.txt:
    find_package(Fix8 REQUIRED)

### CODE REVIEW

**Comment by ido** [comment]
@dakka, could you add pkgconfig support to your build system for fix8?  This CMake module will automatically make use of it (if it's named fix8), so you shouldn't need to change anything in this file once you add pkgconfig support.  (It works without pkgconfig as well...)

**Comment by dakka** [comment]
Ido - I don't have time at the moment, sorry. If you can, please go ahead and add it and I'll review.

**Comment by ido** [comment]
I think this is ready to be merged.  No need for pkgconfig, it works as is.  When/if you ever do add pkgconfig support to the fix8 build system, you won't need to change this file to use it.

**Comment by dakka** [comment]
OK - you may need to make one more change to this then - what sort of license are you releasing this code in? You need to put some sort of statement in there about what people can do with this code. Fix8 is released under LGPLv3.0. If you chose GPL I can't accept the merge. LGPL, BSD, Apache, Boost etc licenses are good examples. Thanks.

**Comment by ido** [comment]
I added the BSD 3-clause which is what CMake is currently released under at the time of writing this.

**Pull request merged**
